clean: true
sdk: iphone
author: Steven Sherry
module: CxValidate
readme: README.md
github_url: https://github.com/CombineExtensions/CxValidate
disable_search: true
theme: fullwidth
build_tool_arguments: [-target, CxValidate]